# Not for the data science only: Generate matrices together with Numpy

In [2]:
import numpy as np

## 1. Sequences

In [7]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [13]:
arr.shape

(6,)

In [8]:
arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [11]:
arr[:, np.newaxis].shape

(6, 1)

In [18]:
np.arange(start = 1,stop = 12, step = 2).reshape(2, 3)

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [19]:
np.arange(1, 12, 2).reshape(2, 3)

array([[ 1,  3,  5],
       [ 7,  9, 11]])

# 2. Random

In [20]:
np.random.random([3,3])

array([[0.0154816 , 0.52251348, 0.0918777 ],
       [0.99782744, 0.71929489, 0.26435086],
       [0.24858931, 0.01793906, 0.17080162]])

In [21]:
np.random.randn(3, 3)

array([[ 2.27777494,  0.82963148, -0.30229966],
       [ 0.46345659,  0.26081925, -3.48677708],
       [-0.71079755,  0.67494053,  0.55780242]])

In [24]:
np.random.randint(0, 3, size=(3, 3))

array([[0, 2, 1],
       [2, 0, 2],
       [0, 0, 0]])

# 3. Distributions

In [31]:
np.linspace(1, 10, 9).reshape(3,3)

array([[ 1.   ,  2.125,  3.25 ],
       [ 4.375,  5.5  ,  6.625],
       [ 7.75 ,  8.875, 10.   ]])

In [32]:
np.logspace(1, 10, 9).reshape(3,3)

array([[1.00000000e+01, 1.33352143e+02, 1.77827941e+03],
       [2.37137371e+04, 3.16227766e+05, 4.21696503e+06],
       [5.62341325e+07, 7.49894209e+08, 1.00000000e+10]])

In [30]:
np.geomspace(1, 10, 9).reshape(3,3)

array([[ 1.        ,  1.33352143,  1.77827941],
       [ 2.37137371,  3.16227766,  4.21696503],
       [ 5.62341325,  7.49894209, 10.        ]])

# 4. Array replication

In [33]:
repl_arr = np.array([1,2,3])

In [34]:
np.tile(repl_arr, [3,1])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [35]:
np.tile(repl_arr, [2,2])

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

# 5. Diagonal matrix

In [37]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [38]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.eye(3, 4, 0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [42]:
np.eye(4, 3, 1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 6. np.zeros()

In [45]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 7. np.ones()

In [46]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 8. np.full()

In [47]:
np.full((3,3), 2, dtype=int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])